import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/navbar";
import Footer from "./Components/footer";
// import { FaWhatsapp } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar  />
        {children}
         {/* Floating WhatsApp Button */}
        {/* <a
          href="https://wa.me/918449188509"
          className="fixed bottom-6 right-6 bg-green-500 text-white p-2 rounded-full shadow-lg hover:scale-110 transition-all"
          target="_blank"
        >
          <FaWhatsapp size={28} />
        </a> */}
        <Footer />
      </body>
    </html>
  );
}
